<?xml version="1.0"?>
<package format="2">
  <name>tyi_planner_bringup</name>
  <version>0.1.0</version>
  <description>Bringup launch files for TYI planner integration.</description>

  <maintainer email="richard@example.com">RichardH</maintainer>
  <license>Proprietary</license>

  <buildtool_depend>catkin</buildtool_depend>

  <exec_depend>ego_planner</exec_depend>
  <exec_depend>tyi_planner_bridge</exec_depend>

  <export/>
</package>
